Repository Normation/rudder-tools, pull requests merged in 2021-03, with the labels that each got.

#653 Fixes #18916: Remove server support for old distro in 7.0
  release-data/rudder-7.0.cson
Labels: qa: Can't merge

#656 Fixes #19042: Add windows target version for build
  release-data/systems.cson
Labels: Ready for merge, Trigger test

#657 Fixes #19059: rework 6.2.3/6.2.4 release notes
  release-data/changelogs/6.1/main.adoc
  release-data/changelogs/6.2/main.adoc
Labels: Trigger test, qa: Can't merge
