Repository Normation/rudder-tools, pull requests merged in 2022-01, with the labels that each got.

#688 Fixes #20502: rudder-setup fails in debian 11
  scripts/rudder-setup/add-repo.sh
Labels: Trigger test

#689 Fixes #20504: rudder-setup ignores NO_HTTPS parameter
  scripts/rudder-setup/add-repo.sh
Labels: Trigger test

#690 Fixes #20510: rudder-setup ignores NO_HTTPS parameter - bis
  scripts/rudder-setup/rudder-setup-src.sh
  scripts/rudder-setup/setup-server.sh
  scripts/rudder-setup/version-test.sh
Labels: Trigger test

#691 Fixes #20517: apt-key is deprecated
  scripts/rudder-setup/add-repo.sh
Labels: Trigger test

#692 Fixes #20544: Follow documentation for debian apt passwords
  scripts/rudder-setup/add-repo.sh
Labels: Trigger test

#694 Fixes #20601: Use python3 for fake report script
  contrib/load-database/load-database.py
Labels: Trigger test

#693 Fixes #20583: Mark 7.0 as final
  release-data/changelogs/7.0/index.adoc
  release-data/rudder-7.0.cson
Labels: Trigger test, WIP

#695 Fixes #20377: AWS inventory hook fails to retrieve instance data when using HVM virtualization
  contrib/inventory-hooks/aws.py
Labels: Trigger test

#696 Fixes #20651: Update release notes
  release-data/changelogs/7.0/images/agent-info.png
  release-data/changelogs/7.0/images/block.png
  release-data/changelogs/7.0/images/drafts.png
  release-data/changelogs/7.0/images/login.png
  release-data/changelogs/7.0/images/pr.png
  release-data/changelogs/7.0/images/rules.png
  release-data/changelogs/7.0/images/secret.png
  release-data/changelogs/7.0/images/theme.png
  release-data/changelogs/7.0/images/wizard.png
  release-data/changelogs/7.0/index.adoc
Labels: Ready for merge, Trigger test
